-- ══════════════════════════════════════════════════
--  BC-11 ~ BC-22 전체 도감 데이터 시드
--  SlimMind V3 바디코드 22종 완성
-- ══════════════════════════════════════════════════

-- BC-11: P-POSTURE형 (자세불균형 척추 교정형)
INSERT OR REPLACE INTO bc_prescriptions (
  bc_code, version, brand_name, tagline, fat_area,
  bc_primary_oneline_reason, bc_cause_story, bc_worsen_word, closing_copy,
  symptom_checklist_json, wrong_methods_json, correct_principles_json,
  recommended_exercises_json, forbidden_exercises_json,
  zone2_bpm, zone2_bpm_v2, hiit_available_week, hiit_available_week_v2,
  recommended_foods_json, forbidden_foods_json, supplement_list_json,
  lifestyle_rules_json, monthly_goals_json,
  b2b_treatments_json, hospital_tests_json,
  recommended_sports_json, forbidden_sports_json,
  macro_ratio_json, macro_story, meal_timing_rule_json,
  sleep_protocol_json, recovery_priority_json, sauna_ok, cryo_ok,
  reassessment_schedule_json, partner_hints_json, is_active
) VALUES (
  'BC-11', 'v1.0', 'P-POSTURE형', '자세불균형 척추 교정형 — 골반 틀어짐·척추측만',
  '척추·골반·코어',
  '허리·골반이 틀어진 건 근력 문제가 아닙니다. 잘못된 자세 습관이 척추 주변 근육을 비대칭으로 굳혀놓은 것입니다.',
  '오랜 좌식 생활과 한쪽으로 기운 자세가 골반을 비틀고 척추 측만을 유발합니다. 코어와 고관절 불균형이 전신 체형 불균형으로 이어집니다.',
  '바르게 앉으면 돼', '자세가 잡히면 체형이 달라집니다. 지금부터 올바른 정렬로 몸의 무게중심을 되찾아가겠습니다.',
  '["허리·골반 통증","한쪽 어깨가 낮음","사진에서 몸이 비대칭","쉽게 피로해짐","오래 앉으면 허리 통증"]',
  '["무작정 코어 운동 강행","복근 강화 크런치 과잉","통증 참고 운동 지속"]',
  '["골반 정렬 먼저","고관절 가동성 회복","호흡 패턴 교정"]',
  '[{"exercise":"맥킨지 신전","sets":3,"reps":"10회","note":"척추 후만 교정"},{"exercise":"데드버그","sets":3,"reps":"12회","note":"코어 안정화"},{"exercise":"힙 힌지","sets":3,"reps":"15회","note":"골반 정렬"}]',
  '[{"exercise":"복근 크런치","reason":"척추 굴곡 과부하"},{"exercise":"레그프레스 과중량","reason":"골반 틀어짐 악화"}]',
  125, 125, '12주 이후 정렬 안정 후', '12주 이후 정렬 안정 후',
  '["뼈 건강: 칼슘 1200mg+비타민D3","항염: 오메가3 EPA 1000mg","근육 이완: 마그네슘 400mg"]',
  '["탄산음료·인산 과다 식품","고염식 (부종·관절압 악화)","카페인 과다 (골밀도 저하)"]',
  '[{"name":"칼슘+비타민D3","dose":"1200mg+2000IU","timing":"식후"},{"name":"마그네슘 글리시네이트","dose":"400mg","timing":"취침전"},{"name":"오메가3","dose":"2g","timing":"식사중"}]',
  '["의자 높이 골반=무릎 수평","모니터 눈높이 맞춤","1시간 착석 후 5분 스트레칭","한쪽 다리 꼬기 금지"]',
  '{"month1":"골반 수평 정렬 회복","month2":"코어 비대칭 감소 50%","month3":"통증 없는 일상 자세 유지"}',
  '{"병원":[{"treatment":"도수치료 (척추교정)","urgency":"high","reason":"골반·척추 정렬 직접 교정"},{"treatment":"체외충격파 (통증 부위)","urgency":"medium","reason":"근막 유착 해소"}],"에스테틱":[{"treatment":"전신 스웨디시·근막이완 마사지","urgency":"high","reason":"비대칭 근육 이완"}],"필라테스":[{"treatment":"척추 정렬 집중 프로그램","urgency":"high","reason":"BC-11 핵심 처방"}],"헬스장":[{"treatment":"기능성 움직임 평가 후 맞춤 PT","urgency":"high","reason":"비대칭 교정 운동 설계"}]}',
  '[{"test":"X-ray 척추 측만각 측정","bc_indication":"BC-11","urgency":"high"},{"test":"골밀도 검사 (DXA)","bc_indication":"BC-11","urgency":"medium"}]',
  '[{"sport":"필라테스 (기구)","condition":"척추 정렬 전문 강사","frequency":"주 3회","reason_bc":"골반·척추 비대칭 직접 교정"},{"sport":"수영 백스트로크","condition":"자유형 금지 초기","frequency":"주 2회","reason_bc":"척추 신전 + 좌우 균형"}]',
  '[{"sport":"테니스·골프","reason":"회전 과부하로 측만 악화"},{"sport":"무거운 스쿼트","reason":"척추 압박 위험"}]',
  '{"protein_pct":30,"fat_pct":35,"carb_pct":35,"fiber_g":25,"water_L":2.0,"mineral_priority":["칼슘","마그네슘","비타민D"]}',
  '뼈와 근육이 함께 균형을 잡는 식단입니다. 칼슘과 마그네슘이 근육 이완과 뼈 건강을 동시에 지원합니다.',
  '{"carb_last":false,"post_meal_walk_min":10,"fasting_allowed":false,"meal_interval_min":300}',
  '{"target_hours":7,"phone_ban_before_sleep_min":30,"bedroom_temp_celsius":19}',
  '[{"method":"온열 매트 (40도, 20분)","priority":1,"reason":"척추 주변 근육 이완"},{"method":"마그네슘 목욕","priority":2,"reason":"근육 경직 완화"}]',
  'true', 'true',
  '{"week4":"골반 수평 개선 여부","week8":"통증 감소 확인","week12":"자세 유지 자율성"}',
  '["도수치료+필라테스 세트 패키지 추천","척추 체크업 서비스와 연계","바른자세 코칭 프로그램"]',
  1
);

-- BC-12: F-FATIGUE형 (만성피로 에너지 고갈형)
INSERT OR REPLACE INTO bc_prescriptions (
  bc_code, version, brand_name, tagline, fat_area,
  bc_primary_oneline_reason, bc_cause_story, bc_worsen_word, closing_copy,
  symptom_checklist_json, wrong_methods_json, correct_principles_json,
  recommended_exercises_json, forbidden_exercises_json,
  zone2_bpm, zone2_bpm_v2, hiit_available_week, hiit_available_week_v2,
  recommended_foods_json, forbidden_foods_json, supplement_list_json,
  lifestyle_rules_json, monthly_goals_json,
  b2b_treatments_json, hospital_tests_json,
  recommended_sports_json, forbidden_sports_json,
  macro_ratio_json, macro_story, meal_timing_rule_json,
  sleep_protocol_json, recovery_priority_json, sauna_ok, cryo_ok,
  reassessment_schedule_json, partner_hints_json, is_active
) VALUES (
  'BC-12', 'v1.0', 'F-FATIGUE형', '만성피로 에너지 고갈형 — 부신 기능 저하·미토콘드리아 부전',
  '전신 (에너지 생산 저하)',
  '아무리 자도 피곤한 건 의지가 약해서가 아닙니다. 세포 에너지 공장인 미토콘드리아가 제대로 작동하지 않고 있기 때문입니다.',
  '장기적 스트레스와 수면 부족으로 부신이 탈진 상태입니다. 코르티솔 곡선이 역전되어 아침엔 무기력하고 밤엔 각성되는 패턴이 나타납니다.',
  '더 열심히 하면 돼', '에너지를 채우면 몸이 달라집니다. 지금은 회복이 곧 다이어트입니다.',
  '["아침 기상이 매우 힘들다","카페인 없이 버티기 어렵다","자고 나도 피로가 풀리지 않는다","집중력·기억력 저하","달콤한 것이 극도로 당긴다"]',
  '["공복 강도 운동","칼로리 급격한 제한","카페인으로 버티기"]',
  '["부신 회복 우선","수면 질 최우선","에너지 생산 영양소 충분 공급"]',
  '[{"exercise":"저강도 걷기","sets":1,"reps":"30분","note":"부신 과부하 없이 미토콘드리아 활성"},{"exercise":"요가·스트레칭","sets":1,"reps":"20분","note":"부교감 신경 활성화"},{"exercise":"수영 느린 페이스","sets":1,"reps":"20분","note":"전신 순환 자극"}]',
  '[{"exercise":"HIIT","reason":"부신 추가 탈진 위험"},{"exercise":"공복 고강도 운동","reason":"코르티솔 폭발"},{"exercise":"무거운 웨이트","reason":"회복 자원 고갈"}]',
  115, 115, '12주 이후 에너지 회복 확인 후', '12주 이후',
  '["코엔자임Q10 300mg","NMN 250mg","비타민B복합체","마그네슘 말레이트 400mg","철분 (헴철)"]',
  '["카페인 오후 2시 이후","알코올","설탕·과당","초가공식품"]',
  '[{"name":"코엔자임Q10","dose":"200mg","timing":"식사중"},{"name":"비타민B12","dose":"1000mcg","timing":"아침"},{"name":"철분(헴철)","dose":"18mg","timing":"공복 또는 비타민C와"},{"name":"마그네슘말레이트","dose":"400mg","timing":"취침전"}]',
  '["기상 직후 햇빛 10분 노출","오후 2시 이후 카페인 금지","수면 7~9시간 절대 우선","과부하 활동 자제"]',
  '{"month1":"수면 질 개선·기상 피로감 감소","month2":"카페인 의존도 50% 감소","month3":"운동 내성 회복·활력 증가"}',
  '{"병원":[{"treatment":"부신 기능 검사 (코르티솔 4회 혈액)","urgency":"high","reason":"부신 피로 정도 정량화"},{"treatment":"마이어스 칵테일 수액 (비타민B·마그네슘·C)","urgency":"high","reason":"즉각적 에너지 회복"}],"에스테틱":[{"treatment":"산소 테라피","urgency":"high","reason":"미토콘드리아 산소 공급"},{"treatment":"신데렐라주사 (티옥트산)","urgency":"medium","reason":"항산화·에너지 회복"}],"헬스장":[{"treatment":"저강도 그룹 운동 (요가·필라테스)","urgency":"high","reason":"부교감 활성화 우선"}]}',
  '[{"test":"코르티솔 일중변동 (타액 4회)","bc_indication":"BC-12","urgency":"high"},{"test":"페리틴·철분·빈혈 패널","bc_indication":"BC-12","urgency":"high"},{"test":"갑상선 (TSH·Free T4)","bc_indication":"BC-12","urgency":"medium"}]',
  '[{"sport":"요가 (인 요가·쿤달리니)","condition":"쾌적한 공간","frequency":"주 3회","reason_bc":"부교감 신경 활성화 최우선"},{"sport":"숲 걷기","condition":"맨발 접지 포함","frequency":"주 3회 30분","reason_bc":"미주신경 자극·스트레스 호르몬 감소"}]',
  '[{"sport":"크로스핏·고강도 서킷","reason":"부신 추가 탈진"},{"sport":"공복 장거리 러닝","reason":"코르티솔+아드레날린 폭발"}]',
  '{"protein_pct":30,"fat_pct":40,"carb_pct":30,"fiber_g":30,"water_L":2.5,"mineral_priority":["마그네슘","철분","B비타민"]}',
  '에너지를 만들려면 재료가 필요합니다. 마그네슘·B비타민·철분이 미토콘드리아의 원료입니다.',
  '{"carb_last":false,"post_meal_walk_min":10,"fasting_allowed":false,"meal_interval_min":240}',
  '{"target_hours":8,"phone_ban_before_sleep_min":90,"bedroom_temp_celsius":18}',
  '[{"method":"수면 우선화 (8시간)","priority":1,"reason":"부신 회복의 90%는 수면"},{"method":"코엔자임Q10 보충","priority":2,"reason":"미토콘드리아 ATP 생산"},{"method":"적외선 사우나 (20분)","priority":3,"reason":"혈액순환·해독"}]',
  'true', 'conditional',
  '{"week4":"기상 피로감 변화","week8":"카페인 의존도 감소","week12":"운동 내성 회복"}',
  '["마이어스 칵테일 수액 패키지 강추","부신 기능 검사 연계 서비스","회복 중심 프리미엄 프로그램"]',
  1
);

-- BC-13: I-IMMUNE형 (면역저하 부종형)
INSERT OR REPLACE INTO bc_prescriptions (
  bc_code, version, brand_name, tagline, fat_area,
  bc_primary_oneline_reason, bc_cause_story, bc_worsen_word, closing_copy,
  symptom_checklist_json, wrong_methods_json, correct_principles_json,
  recommended_exercises_json, forbidden_exercises_json,
  zone2_bpm, zone2_bpm_v2, hiit_available_week, hiit_available_week_v2,
  recommended_foods_json, forbidden_foods_json, supplement_list_json,
  lifestyle_rules_json, monthly_goals_json,
  b2b_treatments_json, hospital_tests_json,
  recommended_sports_json, forbidden_sports_json,
  macro_ratio_json, macro_story, meal_timing_rule_json,
  sleep_protocol_json, recovery_priority_json, sauna_ok, cryo_ok,
  reassessment_schedule_json, partner_hints_json, is_active
) VALUES (
  'BC-13', 'v1.0', 'I-IMMUNE형', '면역저하 부종형 — 림프 정체·만성 염증',
  '전신 부종 (림프·면역계)',
  '자주 붓고 쉽게 아픈 건 면역 시스템이 과부하 상태에서 림프가 제대로 순환하지 못하고 있기 때문입니다.',
  '만성 염증과 림프 정체가 전신 부종을 만듭니다. 면역 과활성화로 인한 자가염증이 체중 감량을 방해합니다.',
  '더 먹으면 면역력이 오른다', '면역이 안정되면 부종도 빠지고 체중도 떨어집니다.',
  '["자주 감기 걸림","전신이 자주 부음","관절이 자주 뻐근","상처 회복이 느림","알레르기 증상 잦음"]',
  '["무리한 운동으로 면역 저하","다이어트 급식제한","고강도 운동 과잉"]',
  '["림프 순환 촉진","항염 식단 우선","수면+회복 충분"]',
  '[{"exercise":"림프 드레나쥐 마사지","sets":1,"reps":"20분","note":"림프 순환 직접 자극"},{"exercise":"수중 걷기","sets":1,"reps":"30분","note":"하체 림프 순환"},{"exercise":"저강도 트레킹","sets":1,"reps":"40분","note":"전신 면역 강화"}]',
  '[{"exercise":"HIIT 고강도","reason":"면역 과부하 위험"},{"exercise":"크로스핏","reason":"염증 마커 상승"}]',
  120, 120, '10주 이후 면역 안정 확인 후', '10주 이후',
  '["비타민C 1000mg","아연 15mg","비타민D3 3000IU","프로바이오틱스 1억 CFU","오메가3 EPA/DHA 2g"]',
  '["설탕·과당 (면역 억제)","트랜스지방","알코올","고염식"]',
  '[{"name":"비타민C","dose":"1000mg","timing":"식후"},{"name":"아연","dose":"15mg","timing":"식사중"},{"name":"비타민D3","dose":"3000IU","timing":"식사중"},{"name":"프로바이오틱스","dose":"1억 CFU","timing":"아침 공복"}]',
  '["손 씻기·위생 철저","수면 7시간 이상","스트레스 관리","냉온 대비 면역 훈련"]',
  '{"month1":"부종 감소·면역 안정","month2":"알레르기 증상 완화","month3":"감염 빈도 감소"}',
  '{"병원":[{"treatment":"면역 글로불린 수치 검사","urgency":"high","reason":"면역 상태 정량화"},{"treatment":"고용량 비타민C 수액","urgency":"medium","reason":"즉각 면역 강화"}],"에스테틱":[{"treatment":"림프 드레나쥐 마사지","urgency":"high","reason":"부종 직접 해소"},{"treatment":"산소 테라피","urgency":"medium","reason":"면역 세포 활성화"}]}',
  '[{"test":"CBC (전혈구 검사)","bc_indication":"BC-13","urgency":"high"},{"test":"CRP·ESR (염증 마커)","bc_indication":"BC-13","urgency":"high"},{"test":"비타민D 혈중 농도","bc_indication":"BC-13","urgency":"medium"}]',
  '[{"sport":"수영","condition":"깨끗한 수질 확인","frequency":"주 3회","reason_bc":"림프 순환 + 면역 강화"},{"sport":"요가","condition":"규칙적","frequency":"주 3회","reason_bc":"부교감 활성화·면역 안정"}]',
  '[{"sport":"크로스핏","reason":"면역 과부하"},{"sport":"수영장 공공 시설 (면역 저하 시)","reason":"감염 위험"}]',
  '{"protein_pct":30,"fat_pct":35,"carb_pct":35,"fiber_g":30,"water_L":2.5,"mineral_priority":["아연","비타민C","비타민D"]}',
  '면역은 장에서 70%가 만들어집니다. 프리바이오틱스 섭취와 항염 식단이 면역의 기반입니다.',
  '{"carb_last":false,"post_meal_walk_min":15,"fasting_allowed":false,"meal_interval_min":240}',
  '{"target_hours":8,"phone_ban_before_sleep_min":60,"bedroom_temp_celsius":20}',
  '[{"method":"수면 우선","priority":1,"reason":"면역 회복 핵심"},{"method":"림프 마사지","priority":2,"reason":"부종 해소"},{"method":"규칙적 냉온 샤워","priority":3,"reason":"면역 강화 훈련"}]',
  'true', 'true',
  '{"week4":"부종 감소 여부","week8":"감기 빈도 변화","week12":"면역 마커 개선"}',
  '["림프 마사지 프로그램 연계","면역 강화 패키지 추천","장 건강 프로그램"]',
  1
);

-- BC-14: SL-SLEEP형 (수면장애 야식형)
INSERT OR REPLACE INTO bc_prescriptions (
  bc_code, version, brand_name, tagline, fat_area,
  bc_primary_oneline_reason, bc_cause_story, bc_worsen_word, closing_copy,
  symptom_checklist_json, wrong_methods_json, correct_principles_json,
  recommended_exercises_json, forbidden_exercises_json,
  zone2_bpm, zone2_bpm_v2, hiit_available_week, hiit_available_week_v2,
  recommended_foods_json, forbidden_foods_json, supplement_list_json,
  lifestyle_rules_json, monthly_goals_json,
  b2b_treatments_json, hospital_tests_json,
  recommended_sports_json, forbidden_sports_json,
  macro_ratio_json, macro_story, meal_timing_rule_json,
  sleep_protocol_json, recovery_priority_json, sauna_ok, cryo_ok,
  reassessment_schedule_json, partner_hints_json, is_active
) VALUES (
  'BC-14', 'v1.0', 'SL-SLEEP형', '수면장애 야식형 — 멜라토닌 교란·야간 식욕 호르몬 과잉',
  '복부 (야식 지방 축적)',
  '밤에 배가 고프고 잠 못 드는 건 의지력 문제가 아닙니다. 멜라토닌이 교란되고 그렐린이 과분비되어 뇌가 밤에 음식을 찾도록 프로그래밍되어 있기 때문입니다.',
  '늦은 취침과 스마트폰 블루라이트로 멜라토닌 분비가 차단됩니다. 수면 부족은 그렐린(식욕 자극)을 올리고 렙틴(포만감)을 낮춰 야식 욕구를 증폭시킵니다.',
  '야식 좀 먹어도 돼', '수면이 바뀌면 살이 빠집니다. 성장호르몬은 잠든 후 90분에 폭발합니다.',
  '["잠들기 어렵다","밤에 배가 고프다","기상 후 붓기가 심하다","낮에 졸리고 밤에 각성","야식 없이 못 잠"]',
  '["수면제 의존","야식 억제 의지력으로만 해결","낮잠 과다"]',
  '["취침 루틴 구축","블루라이트 차단","저녁 식사 타이밍 앞당기기"]',
  '[{"exercise":"저녁 7시 이전 가벼운 걷기","sets":1,"reps":"30분","note":"체온 상승 후 하강으로 수면 유도"},{"exercise":"요가 닌드라","sets":1,"reps":"20분","note":"수면 전 부교감 활성화"}]',
  '[{"exercise":"저녁 고강도 운동","reason":"코르티솔 상승으로 수면 방해"},{"exercise":"취침 직전 운동","reason":"각성 상태 유발"}]',
  125, 125, '8주 이후 수면 패턴 안정 후', '8주 이후',
  '["마그네슘 글리시네이트 400mg","L-테아닌 200mg","멜라토닌 0.5mg (단기)","트립토판 500mg","GABA 500mg"]',
  '["카페인 (오후 1시 이후)","알코올","야식 탄수화물","블루라이트 (취침 1시간 전)"]',
  '[{"name":"마그네슘 글리시네이트","dose":"400mg","timing":"취침 1시간 전"},{"name":"L-테아닌","dose":"200mg","timing":"취침 30분 전"},{"name":"트립토판","dose":"500mg","timing":"저녁 식사 후"}]',
  '["취침 시간 고정 (23시 이전)","기상 시간 고정 (7시 이전)","침실 온도 18~19도","취침 전 1시간 블루라이트 차단","저녁 8시 이후 음식 금지"]',
  '{"month1":"수면 시작 시간 30분 앞당기기","month2":"야식 빈도 주 1회 이하","month3":"기상 후 부기 감소"}',
  '{"병원":[{"treatment":"수면다원검사 (수면무호흡 확인)","urgency":"medium","reason":"수면 구조 정량화"},{"treatment":"멜라토닌 검사 + 광치료","urgency":"medium","reason":"일주기 리듬 교정"}],"에스테틱":[{"treatment":"아로마 수면 마사지","urgency":"medium","reason":"부교감 활성화"},{"treatment":"두피 마사지","urgency":"low","reason":"긴장 해소·수면 유도"}]}',
  '[{"test":"수면다원검사","bc_indication":"BC-14","urgency":"medium"},{"test":"코르티솔 일중변동","bc_indication":"BC-14","urgency":"medium"}]',
  '[{"sport":"오전 걷기 (햇빛 노출)","condition":"기상 후 1시간 이내","frequency":"매일 30분","reason_bc":"일주기 리듬 재설정"},{"sport":"요가 니드라","condition":"취침 전","frequency":"매일 20분","reason_bc":"수면 진입 보조"}]',
  '[{"sport":"저녁 고강도 운동","reason":"코르티솔 상승 수면 방해"},{"sport":"저녁 9시 이후 운동","reason":"각성 상태 유발"}]',
  '{"protein_pct":30,"fat_pct":35,"carb_pct":35,"fiber_g":25,"water_L":2.0,"mineral_priority":["마그네슘","트립토판","B6"]}',
  '트립토판이 세로토닌이 되고 세로토닌이 멜라토닌이 됩니다. 저녁 식사에 트립토판 풍부 식품을 넣으세요.',
  '{"carb_last":false,"post_meal_walk_min":15,"fasting_allowed":false,"meal_interval_min":240,"evening_cutoff_hour":20}',
  '{"target_hours":8,"phone_ban_before_sleep_min":60,"bedroom_temp_celsius":18,"blackout_curtain":true}',
  '[{"method":"수면 루틴 고정","priority":1,"reason":"일주기 리듬 안정화"},{"method":"마그네슘 취침 전 복용","priority":2,"reason":"근육 이완·수면 질 향상"}]',
  'true', 'false',
  '{"week4":"수면 시작 시간 개선","week8":"야식 충동 감소","week12":"수면 깊이 개선"}',
  '["수면 마사지 패키지","아로마 테라피 연계","수면 코칭 프로그램"]',
  1
);

-- BC-15: D-DETOX형 (독소축적 간기능 저하형)
INSERT OR REPLACE INTO bc_prescriptions (
  bc_code, version, brand_name, tagline, fat_area,
  bc_primary_oneline_reason, bc_cause_story, bc_worsen_word, closing_copy,
  symptom_checklist_json, wrong_methods_json, correct_principles_json,
  recommended_exercises_json, forbidden_exercises_json,
  zone2_bpm, zone2_bpm_v2, hiit_available_week, hiit_available_week_v2,
  recommended_foods_json, forbidden_foods_json, supplement_list_json,
  lifestyle_rules_json, monthly_goals_json,
  b2b_treatments_json, hospital_tests_json,
  recommended_sports_json, forbidden_sports_json,
  macro_ratio_json, macro_story, meal_timing_rule_json,
  sleep_protocol_json, recovery_priority_json, sauna_ok, cryo_ok,
  reassessment_schedule_json, partner_hints_json, is_active
) VALUES (
  'BC-15', 'v1.0', 'D-DETOX형', '독소축적 간기능 저하형 — 비알코올성 지방간·해독 부전',
  '복부 (간 지방·독소)',
  '살이 잘 안 빠지는 이유가 의지 문제가 아닐 수 있습니다. 간이 지방을 대사하는 대신 독소 처리에 바쁘기 때문입니다.',
  '환경 독소·가공식품·음주가 간의 해독 능력을 과부하시킵니다. 간 기능이 저하되면 지방 대사 효율이 급감하고 중성지방이 쌓입니다.',
  '술 끊으면 금방 빠져', '간을 회복시키면 지방 대사 엔진이 살아납니다.',
  '["오전 피로감·무기력","황달·눈 노란빛","복부 팽만·소화불량","피부 가려움·발진","음주 후 회복 느림"]',
  '["다이어트 보조제 남용","알코올 지속","고지방 가공식품"]',
  '["간 해독 영양소 공급","알코올 완전 차단","항산화 식단 우선"]',
  '[{"exercise":"저강도 걷기","sets":1,"reps":"40분","note":"간 혈류 증가·지방산 산화"},{"exercise":"수영","sets":1,"reps":"30분","note":"전신 유산소·간 부담 최소"}]',
  '[{"exercise":"고강도 무산소","reason":"젖산 과잉→간 부담 증가"},{"exercise":"공복 장거리 유산소","reason":"지방산 과잉 방출→간 과부하"}]',
  120, 120, '10주 이후 간 기능 개선 확인 후', '10주 이후',
  '["밀크씨슬 (실리마린 140mg)","NAC (N-아세틸시스테인) 600mg","비타민E 400IU","알파리포산 300mg","콜린 500mg"]',
  '["알코올 (완전 차단)","과당·액상과당","트랜스지방·튀김","아세트아미노펜 장기복용"]',
  '[{"name":"밀크씨슬","dose":"실리마린 140mg","timing":"식전"},{"name":"NAC","dose":"600mg","timing":"식전"},{"name":"알파리포산","dose":"300mg","timing":"식사중"},{"name":"비타민E","dose":"400IU","timing":"식사중"}]',
  '["알코올 완전 차단","하루 물 2.5L 이상","유기농 채소 위주","가공식품 최소화"]',
  '{"month1":"간 효소 수치 (ALT·AST) 감소","month2":"복부 팽만 완화","month3":"지방 대사 회복·체중 감소 시작"}',
  '{"병원":[{"treatment":"간 기능 검사 (ALT·AST·GGT)","urgency":"high","reason":"간 손상 정도 정량화"},{"treatment":"알파리포산 수액 + 간 보호 수액","urgency":"high","reason":"즉각 간세포 보호"}],"에스테틱":[{"treatment":"적외선 사우나","urgency":"medium","reason":"피부 해독 경로 활성화"},{"treatment":"림프 드레나쥐","urgency":"medium","reason":"독소 배출 촉진"}]}',
  '[{"test":"간 기능 패널 (ALT·AST·GGT·ALP)","bc_indication":"BC-15","urgency":"high"},{"test":"복부 초음파 (지방간 확인)","bc_indication":"BC-15","urgency":"high"},{"test":"중성지방·HDL","bc_indication":"BC-15","urgency":"medium"}]',
  '[{"sport":"저강도 걷기","condition":"식후 30분","frequency":"매일 40분","reason_bc":"간 혈류 증가"},{"sport":"수영","condition":"공복 제외","frequency":"주 3회","reason_bc":"지방산 산화 촉진"}]',
  '[{"sport":"고강도 웨이트","reason":"간 부담 증가"},{"sport":"공복 러닝","reason":"지방산 과잉 방출"}]',
  '{"protein_pct":25,"fat_pct":30,"carb_pct":45,"fiber_g":35,"water_L":2.5,"mineral_priority":["콜린","셀레늄","비타민E"]}',
  '간은 매일 500가지 이상의 기능을 합니다. 간이 쉬어야 지방을 태울 수 있습니다.',
  '{"carb_last":false,"post_meal_walk_min":30,"fasting_allowed":false,"meal_interval_min":300}',
  '{"target_hours":8,"phone_ban_before_sleep_min":60,"bedroom_temp_celsius":19}',
  '[{"method":"알코올 완전 금지","priority":1,"reason":"간 해독 가장 큰 부담 제거"},{"method":"밀크씨슬 복용","priority":2,"reason":"간세포 직접 보호"},{"method":"적외선 사우나","priority":3,"reason":"피부 해독 경로 활성"}]',
  'true', 'true',
  '{"week4":"소화불량·팽만 변화","week8":"ALT·AST 재검사","week12":"지방 대사 회복"}',
  '["간 해독 패키지 프로그램","해독 수액 패키지 추천","디톡스 다이어트 연계"]',
  1
);

-- BC-16: M-METABOLIC형 (신진대사 저하 에너지 부족형)
INSERT OR REPLACE INTO bc_prescriptions (
  bc_code, version, brand_name, tagline, fat_area,
  bc_primary_oneline_reason, bc_cause_story, bc_worsen_word, closing_copy,
  symptom_checklist_json, wrong_methods_json, correct_principles_json,
  recommended_exercises_json, forbidden_exercises_json,
  zone2_bpm, zone2_bpm_v2, hiit_available_week, hiit_available_week_v2,
  recommended_foods_json, forbidden_foods_json, supplement_list_json,
  lifestyle_rules_json, monthly_goals_json,
  b2b_treatments_json, hospital_tests_json,
  recommended_sports_json, forbidden_sports_json,
  macro_ratio_json, macro_story, meal_timing_rule_json,
  sleep_protocol_json, recovery_priority_json, sauna_ok, cryo_ok,
  reassessment_schedule_json, partner_hints_json, is_active
) VALUES (
  'BC-16', 'v1.0', 'M-METABOLIC형', '신진대사 저하 에너지 부족형 — 갑상선 기능 저하·기초대사 감소',
  '전신 (기초대사율 저하)',
  '추위를 많이 타고 살이 잘 안 빠지는 건 나태함이 아닙니다. 갑상선 호르몬이 몸의 에너지 연소 속도를 조절하는데, 그 스위치가 느리게 켜져 있는 것입니다.',
  '갑상선 기능 저하 또는 요요로 인한 기초대사율 감소로 칼로리 소비 자체가 줄어든 상태입니다. 식사량을 줄여도 살이 안 빠지는 이유입니다.',
  '덜 먹으면 빠진다', '대사 속도를 올리면 같은 양을 먹어도 살이 빠집니다.',
  '["항상 춥다·추위를 탄다","조금 먹어도 살이 찐다","변비가 잦다","머리카락·눈썹이 빠진다","피부가 건조하고 푸석하다"]',
  '["칼로리 급감으로 대사 더 낮추기","공복 장시간 유지","유산소만 과잉"]',
  '["근육 유지로 기초대사 유지","단백질 충분 섭취","갑상선 영양소 공급"]',
  '[{"exercise":"근력 운동 (대근육 중심)","sets":4,"reps":"8~10회","note":"기초대사율 유지의 핵심"},{"exercise":"존2 유산소","sets":1,"reps":"40분","note":"지방 산화 효율 최대화"},{"exercise":"HIIT (8주 이후)","sets":1,"reps":"20분","note":"기초대사율 추가 상승"}]',
  '[{"exercise":"과도한 유산소만","reason":"근육 손실로 기초대사 추가 저하"},{"exercise":"극저칼로리 병행","reason":"대사 추가 감소"}]',
  130, 130, '8주 이후 갑상선 안정 확인 후', '8주 이후',
  '["셀레늄 200mcg (갑상선 효소 보조)","아연 15mg","요오드 150mcg","비타민D3 3000IU","타이로신 500mg"]',
  '["글루텐 (하시모토 갑상선염 악화)","대두 과잉 (갑상선 호르몬 흡수 방해)","생 십자화과 과잉","칼로리 극단 제한"]',
  '[{"name":"셀레늄","dose":"200mcg","timing":"식사중"},{"name":"아연","dose":"15mg","timing":"식사중"},{"name":"비타민D3","dose":"3000IU","timing":"식사중"},{"name":"타이로신","dose":"500mg","timing":"아침 공복"}]',
  '["아침 기상 후 스트레칭 10분","햇빛 노출 30분 이상","냉온 샤워로 대사 자극","식사 규칙적 3회"]',
  '{"month1":"기초체온 상승 (36.5도 목표)","month2":"변비 개선·장 운동성 회복","month3":"기초대사율 5~10% 상승"}',
  '{"병원":[{"treatment":"갑상선 기능 검사 (TSH·Free T4·T3)","urgency":"high","reason":"갑상선 저하 정량화"},{"treatment":"갑상선 호르몬 보충 (의사 처방)","urgency":"medium","reason":"약물 치료 필요 여부 판단"}],"에스테틱":[{"treatment":"적외선 사우나","urgency":"medium","reason":"체온 상승·대사 자극"},{"treatment":"고주파 온열 치료","urgency":"medium","reason":"기초체온 상승"}]}',
  '[{"test":"갑상선 패널 (TSH·Free T4·T3·anti-TPO)","bc_indication":"BC-16","urgency":"high"},{"test":"기초대사율 측정 (인바디)","bc_indication":"BC-16","urgency":"high"},{"test":"혈중 셀레늄·아연","bc_indication":"BC-16","urgency":"medium"}]',
  '[{"sport":"근력 운동 (PT)","condition":"대근육 우선","frequency":"주 3회","reason_bc":"기초대사율 유지 핵심"},{"sport":"걷기 + 경사 트레드밀","condition":"체온 상승 확인","frequency":"주 4회","reason_bc":"갑상선 혈류 자극"}]',
  '[{"sport":"과도한 유산소","reason":"근육 손실로 대사 추가 저하"},{"sport":"칼로리 제한과 병행 러닝","reason":"대사 억제 심화"}]',
  '{"protein_pct":35,"fat_pct":35,"carb_pct":30,"fiber_g":25,"water_L":2.0,"mineral_priority":["셀레늄","아연","요오드"]}',
  '갑상선은 몸의 온도 조절기입니다. 셀레늄·아연이 갑상선 효소의 연료입니다.',
  '{"carb_last":true,"post_meal_walk_min":15,"fasting_allowed":false,"meal_interval_min":240}',
  '{"target_hours":8,"phone_ban_before_sleep_min":60,"bedroom_temp_celsius":20}',
  '[{"method":"규칙적 식사 (대사 리듬)","priority":1,"reason":"갑상선 호르몬 분비 리듬 안정"},{"method":"근력 운동 유지","priority":2,"reason":"기초대사율 유지"},{"method":"적외선 사우나","priority":3,"reason":"체온 상승·대사 자극"}]',
  'true', 'true',
  '{"week4":"기초체온 변화","week8":"갑상선 기능 재검사","week12":"대사율 개선 확인"}',
  '["갑상선 검사 연계 서비스","온열 치료 패키지","대사 회복 전문 프로그램"]',
  1
);

-- BC-17: W-WATER형 (수분 불균형 부종형)
INSERT OR REPLACE INTO bc_prescriptions (
  bc_code, version, brand_name, tagline, fat_area,
  bc_primary_oneline_reason, bc_cause_story, bc_worsen_word, closing_copy,
  symptom_checklist_json, wrong_methods_json, correct_principles_json,
  recommended_exercises_json, forbidden_exercises_json,
  zone2_bpm, zone2_bpm_v2, hiit_available_week, hiit_available_week_v2,
  recommended_foods_json, forbidden_foods_json, supplement_list_json,
  lifestyle_rules_json, monthly_goals_json,
  b2b_treatments_json, hospital_tests_json,
  recommended_sports_json, forbidden_sports_json,
  macro_ratio_json, macro_story, meal_timing_rule_json,
  sleep_protocol_json, recovery_priority_json, sauna_ok, cryo_ok,
  reassessment_schedule_json, partner_hints_json, is_active
) VALUES (
  'BC-17', 'v1.0', 'W-WATER형', '수분 불균형 부종형 — 나트륨 과잉·신장 기능 저하',
  '전신 부종 (수분 저류)',
  '저녁에 신발이 꽉 끼고 아침에 얼굴이 붓는 건 지방이 아닙니다. 나트륨-칼륨 밸런스가 무너져 세포간질에 수분이 갇혀 있기 때문입니다.',
  '고염식과 부족한 수분 섭취가 나트륨-칼륨 불균형을 만듭니다. 신장이 제대로 여과하지 못하면 수분이 조직에 쌓여 부종이 됩니다.',
  '물을 덜 마시면 부기가 빠진다', '물을 더 마셔야 부기가 빠집니다. 물이 나트륨을 씻어냅니다.',
  '["저녁에 발·발목이 붓는다","아침에 얼굴·손이 붓는다","짠 음식을 자주 먹는다","소변 횟수가 적다","체중이 하루 1kg 이상 변동"]',
  '["물 마시기 줄이기","이뇨제 남용","고염식 지속"]',
  '["나트륨 제한 (<1500mg/일)","칼륨 섭취 증가","수분 충분히"]',
  '[{"exercise":"수중 운동·수영","sets":1,"reps":"30분","note":"수압으로 림프·정맥 순환 개선"},{"exercise":"하체 올리기 운동","sets":3,"reps":"15분","note":"하지 정맥 순환 촉진"},{"exercise":"걷기","sets":1,"reps":"40분","note":"근육 펌프 작용으로 림프 순환"}]',
  '[{"exercise":"고강도 웨이트 (초기)","reason":"근손상→염증→부종 악화"},{"exercise":"더운 환경 운동","reason":"과도한 땀으로 전해질 불균형"}]',
  125, 125, '8주 이후', '8주 이후',
  '["칼륨 보충 (바나나·아보카도)","마그네슘 400mg","비타민B6 50mg (이뇨 효과)","댄디라이온 티 (천연 이뇨)"]',
  '["고염식 (가공식품·라면·소금)","알코올","카페인 과다","MSG 과잉"]',
  '[{"name":"마그네슘","dose":"400mg","timing":"취침전"},{"name":"비타민B6","dose":"50mg","timing":"아침"},{"name":"칼륨 (식품으로)","dose":"3500mg","timing":"매끼"}]',
  '["하루 물 2.5L (운동시 3L)","나트륨 1500mg 이하","칼륨 풍부 채소 매끼","다리 올리고 자기"]',
  '{"month1":"아침 부기 50% 감소","month2":"저녁 발 부기 완화","month3":"체중 변동 안정화"}',
  '{"병원":[{"treatment":"신장 기능 검사 (BUN·크레아티닌)","urgency":"medium","reason":"신장 여과 기능 확인"},{"treatment":"전해질 패널 검사","urgency":"medium","reason":"나트륨·칼륨 불균형 정량화"}],"에스테틱":[{"treatment":"림프 드레나쥐 마사지","urgency":"high","reason":"부종 직접 해소"},{"treatment":"경락 마사지","urgency":"medium","reason":"수분 순환 촉진"}]}',
  '[{"test":"신장 기능 (BUN·크레아티닌·GFR)","bc_indication":"BC-17","urgency":"medium"},{"test":"전해질 (Na·K·Cl)","bc_indication":"BC-17","urgency":"medium"}]',
  '[{"sport":"수영·수중 에어로빅","condition":"체온 조절 환경","frequency":"주 3회","reason_bc":"수압 부종 해소"},{"sport":"하체 근력 운동","condition":"규칙적","frequency":"주 3회","reason_bc":"정맥 펌프 작용"}]',
  '[{"sport":"열기 환경 고강도 운동","reason":"전해질 불균형 악화"},{"sport":"수분 제한 후 운동","reason":"신장 부담"}]',
  '{"protein_pct":25,"fat_pct":30,"carb_pct":45,"fiber_g":30,"water_L":2.5,"mineral_priority":["칼륨","마그네슘","B6"]}',
  '나트륨 1이 물 분자 50개를 붙잡습니다. 칼륨이 나트륨을 밀어내고 물을 방출시킵니다.',
  '{"carb_last":false,"post_meal_walk_min":20,"fasting_allowed":false,"meal_interval_min":240}',
  '{"target_hours":7,"phone_ban_before_sleep_min":30,"bedroom_temp_celsius":19}',
  '[{"method":"다리 올리기 (15분)","priority":1,"reason":"하지 부종 배액"},{"method":"림프 마사지","priority":2,"reason":"부종 직접 해소"},{"method":"저염 식단 전환","priority":3,"reason":"근본 원인 제거"}]',
  'true', 'true',
  '{"week4":"아침 부기 변화","week8":"저녁 부종 개선","week12":"전해질 균형 안정"}',
  '["림프 드레나쥐 패키지","전해질 검사 연계","저염 식단 코칭"]',
  1
);

-- BC-18: U-URIC형 (요산 과잉 통풍 예방형)
INSERT OR REPLACE INTO bc_prescriptions (
  bc_code, version, brand_name, tagline, fat_area,
  bc_primary_oneline_reason, bc_cause_story, bc_worsen_word, closing_copy,
  symptom_checklist_json, wrong_methods_json, correct_principles_json,
  recommended_exercises_json, forbidden_exercises_json,
  zone2_bpm, zone2_bpm_v2, hiit_available_week, hiit_available_week_v2,
  recommended_foods_json, forbidden_foods_json, supplement_list_json,
  lifestyle_rules_json, monthly_goals_json,
  b2b_treatments_json, hospital_tests_json,
  recommended_sports_json, forbidden_sports_json,
  macro_ratio_json, macro_story, meal_timing_rule_json,
  sleep_protocol_json, recovery_priority_json, sauna_ok, cryo_ok,
  reassessment_schedule_json, partner_hints_json, is_active
) VALUES (
  'BC-18', 'v1.0', 'U-URIC형', '요산 과잉 통풍 예방형 — 퓨린 과잉·신장 배설 저하',
  '복부·관절 (요산 결정)',
  '발가락·발목 관절이 갑자기 붓고 아픈 건 요산 결정이 관절에 쌓였기 때문입니다. 퓨린 대사 과잉과 신장 배설 저하가 원인입니다.',
  '육류·맥주·과당의 과잉 섭취로 요산이 혈중에 쌓입니다. 신장이 충분히 배설하지 못하면 요산 결정이 관절에 침착되어 극심한 통증을 유발합니다.',
  '고기 먹으면 힘이 난다', '요산을 낮추면 관절도 살고 체중도 빠집니다.',
  '["발가락·발목 갑작스런 통증","관절 부종","혈중 요산 수치 7 이상","술 마신 다음날 관절 통증","붉은 고기 많이 먹는다"]',
  '["퓨린 식품 무제한 섭취","고강도 운동 + 수분 부족","알코올 지속"]',
  '["저퓨린 식단","충분한 수분 (3L)","요산 배설 촉진"]',
  '[{"exercise":"수영·자전거","sets":1,"reps":"40분","note":"관절 충격 없이 대사 촉진"},{"exercise":"걷기","sets":1,"reps":"30분","note":"저충격 유산소"},{"exercise":"수중 에어로빅","sets":1,"reps":"30분","note":"관절 부담 최소"}]',
  '[{"exercise":"달리기 충격 운동","reason":"관절 충격으로 통풍 발작 유발"},{"exercise":"고강도 탈수 운동","reason":"요산 농도 상승"}]',
  120, 120, '12주 이후 요산 수치 정상화 후', '12주 이후',
  '["비타민C 1000mg (요산 배설 촉진)","체리 추출물 500mg","알파리포산 300mg","물 하루 3L"]',
  '["맥주·알코올","붉은 고기·내장류","새우·조개·굴 등 해산물","과당·액상과당","멸치·정어리 (퓨린 최고)"]',
  '[{"name":"비타민C","dose":"1000mg","timing":"식후"},{"name":"체리 추출물","dose":"500mg","timing":"식사중"},{"name":"알파리포산","dose":"300mg","timing":"식사중"}]',
  '["물 3L 이상 매일","알코올 완전 금지 (급성기)","붉은 고기 주 2회 이하","체리·블루베리 매일"]',
  '{"month1":"혈중 요산 0.5 이상 감소","month2":"관절 통증 빈도 감소","month3":"요산 정상 범위 (6 이하)"}',
  '{"병원":[{"treatment":"혈중 요산 측정","urgency":"high","reason":"요산 수치 정량화"},{"treatment":"요산 저하제 (알로퓨리놀) 처방","urgency":"medium","reason":"약물 치료 필요 여부"}],"에스테틱":[{"treatment":"관절 냉찜질 테라피","urgency":"medium","reason":"통풍 발작 시 급성 완화"},{"treatment":"림프 드레나쥐","urgency":"medium","reason":"요산 배설 보조"}]}',
  '[{"test":"혈중 요산 (uric acid)","bc_indication":"BC-18","urgency":"high"},{"test":"신장 기능 (크레아티닌·GFR)","bc_indication":"BC-18","urgency":"high"},{"test":"요산 24시간 소변 검사","bc_indication":"BC-18","urgency":"medium"}]',
  '[{"sport":"수영","condition":"관절 충격 없음","frequency":"주 3회","reason_bc":"관절 부담 없이 대사 촉진"},{"sport":"자전거","condition":"실내 사이클 가능","frequency":"주 3회","reason_bc":"저충격 유산소"}]',
  '[{"sport":"달리기","reason":"관절 충격 통풍 발작"},{"sport":"고강도 웨이트","reason":"요산 급증 위험"}]',
  '{"protein_pct":20,"fat_pct":35,"carb_pct":45,"fiber_g":30,"water_L":3.0,"mineral_priority":["비타민C","칼륨","마그네슘"]}',
  '퓨린은 단백질에 많습니다. 식물성 단백질로 전환하고 체리가 요산 배설을 돕습니다.',
  '{"carb_last":false,"post_meal_walk_min":20,"fasting_allowed":false,"meal_interval_min":300}',
  '{"target_hours":8,"phone_ban_before_sleep_min":60,"bedroom_temp_celsius":19}',
  '[{"method":"수분 3L 유지","priority":1,"reason":"요산 신장 배설 최대화"},{"method":"알코올 금지","priority":2,"reason":"요산 배설 차단 원인 제거"},{"method":"체리·블루베리 섭취","priority":3,"reason":"요산 저하 자연 성분"}]',
  'true', 'false',
  '{"week4":"혈중 요산 재측정","week8":"관절 통증 빈도","week12":"요산 정상화 확인"}',
  '["요산 검사 연계 서비스","관절 케어 프로그램","저퓨린 식단 코칭"]',
  1
);

-- BC-19: GI-GUT형 (장 건강 이상 변비·과민성형)
INSERT OR REPLACE INTO bc_prescriptions (
  bc_code, version, brand_name, tagline, fat_area,
  bc_primary_oneline_reason, bc_cause_story, bc_worsen_word, closing_copy,
  symptom_checklist_json, wrong_methods_json, correct_principles_json,
  recommended_exercises_json, forbidden_exercises_json,
  zone2_bpm, zone2_bpm_v2, hiit_available_week, hiit_available_week_v2,
  recommended_foods_json, forbidden_foods_json, supplement_list_json,
  lifestyle_rules_json, monthly_goals_json,
  b2b_treatments_json, hospital_tests_json,
  recommended_sports_json, forbidden_sports_json,
  macro_ratio_json, macro_story, meal_timing_rule_json,
  sleep_protocol_json, recovery_priority_json, sauna_ok, cryo_ok,
  reassessment_schedule_json, partner_hints_json, is_active
) VALUES (
  'BC-19', 'v1.0', 'GI-GUT형', '장 건강 이상 변비·과민성 장형 — 장내미생물 불균형·장 투과성 증가',
  '복부 팽만 (장내 가스·숙변)',
  '배가 항상 빵빵하고 변비가 반복되는 건 장내미생물 생태계가 무너졌기 때문입니다. 좋은 균이 줄고 나쁜 균이 늘면 장이 제대로 움직이지 않습니다.',
  '항생제·가공식품·스트레스로 장내미생물 다양성이 감소합니다. 장 투과성(Leaky Gut)이 증가하면 독소가 혈류로 유입되어 전신 염증을 유발합니다.',
  '장 문제는 그냥 참으면 돼', '장이 회복되면 면역·체중·기분이 함께 좋아집니다.',
  '["변비 또는 설사 반복","복부 팽만·가스","음식 민감성 증가","피부 트러블","불안·우울 경향"]',
  '["항생제 남용","고가공식품 지속","섬유소 섭취 부족"]',
  '["프로바이오틱스+프리바이오틱스","섬유소 35g 이상","항염 식단"]',
  '[{"exercise":"걷기 (식후)","sets":1,"reps":"20분","note":"장 연동 운동 자극"},{"exercise":"복부 마사지","sets":1,"reps":"10분","note":"시계방향으로 장 자극"},{"exercise":"요가 (비틀기 자세)","sets":1,"reps":"15분","note":"장 연동 운동 촉진"}]',
  '[{"exercise":"식후 즉시 고강도","reason":"혈류 근육 집중→장 혈류 감소"},{"exercise":"과도한 유산소 공복","reason":"코르티솔→장 투과성 악화"}]',
  125, 125, '8주 이후 장 기능 안정 후', '8주 이후',
  '["프로바이오틱스 (100억 CFU 이상)","프리바이오틱스 (이눌린)","L-글루타민 5g","소화 효소 복합체","마그네슘 시트레이트 (변비 시)"]',
  '["글루텐 (장 투과성 악화)","유제품 (유당불내증 시)","인공감미료 (장내균 억제)","알코올","고가공식품"]',
  '[{"name":"프로바이오틱스","dose":"100억 CFU","timing":"아침 공복"},{"name":"L-글루타민","dose":"5g","timing":"공복"},{"name":"소화효소","dose":"1캡슐","timing":"식사중"},{"name":"마그네슘 시트레이트","dose":"300mg","timing":"취침전"}]',
  '["식사 천천히 씹기 (30회)","스트레스 최소화","규칙적 식사 시간","충분한 수분"]',
  '{"month1":"변비 빈도 50% 감소","month2":"복부 팽만 완화","month3":"장내 환경 안정"}',
  '{"병원":[{"treatment":"장내미생물 검사 (마이크로바이옴)","urgency":"medium","reason":"장내 균총 상태 파악"},{"treatment":"대장 내시경","urgency":"medium","reason":"기질적 이상 확인"}],"에스테틱":[{"treatment":"복부 림프 마사지","urgency":"medium","reason":"장 연동 운동 보조"},{"treatment":"경락 복부 마사지","urgency":"medium","reason":"소화기 혈류 개선"}]}',
  '[{"test":"장내미생물 검사","bc_indication":"BC-19","urgency":"medium"},{"test":"칼프로텍틴 (장 염증 마커)","bc_indication":"BC-19","urgency":"medium"},{"test":"식품 알레르기·불내증 검사","bc_indication":"BC-19","urgency":"low"}]',
  '[{"sport":"걷기 (식후 20분)","condition":"매 식후","frequency":"매일","reason_bc":"장 연동 운동 직접 자극"},{"sport":"요가 (비틀기)","condition":"빈속","frequency":"주 3회","reason_bc":"장 기계적 자극"}]',
  '[{"sport":"공복 고강도","reason":"코르티솔→장 투과성 악화"},{"sport":"과식 후 즉시 운동","reason":"소화 방해"}]',
  '{"protein_pct":25,"fat_pct":30,"carb_pct":45,"fiber_g":35,"water_L":2.5,"mineral_priority":["마그네슘","아연","비타민D"]}',
  '장내미생물은 먹이를 먹어야 삽니다. 프리바이오틱스(식이섬유)가 좋은 균의 먹이입니다.',
  '{"carb_last":false,"post_meal_walk_min":20,"fasting_allowed":false,"meal_interval_min":240}',
  '{"target_hours":7,"phone_ban_before_sleep_min":60,"bedroom_temp_celsius":20}',
  '[{"method":"프로바이오틱스 매일 복용","priority":1,"reason":"장내균 다양성 회복"},{"method":"식이섬유 35g 이상","priority":2,"reason":"좋은 균의 먹이 공급"},{"method":"L-글루타민 보충","priority":3,"reason":"장 상피 세포 수복"}]',
  'true', 'false',
  '{"week4":"변비 빈도 변화","week8":"복부 팽만 감소","week12":"장내 환경 안정"}',
  '["장 건강 프로그램 패키지","마이크로바이옴 검사 연계","소화기 전문 식단 코칭"]',
  1
);

-- BC-20: ST-STOMACH형 (스트레스성 위장장애형)
INSERT OR REPLACE INTO bc_prescriptions (
  bc_code, version, brand_name, tagline, fat_area,
  bc_primary_oneline_reason, bc_cause_story, bc_worsen_word, closing_copy,
  symptom_checklist_json, wrong_methods_json, correct_principles_json,
  recommended_exercises_json, forbidden_exercises_json,
  zone2_bpm, zone2_bpm_v2, hiit_available_week, hiit_available_week_v2,
  recommended_foods_json, forbidden_foods_json, supplement_list_json,
  lifestyle_rules_json, monthly_goals_json,
  b2b_treatments_json, hospital_tests_json,
  recommended_sports_json, forbidden_sports_json,
  macro_ratio_json, macro_story, meal_timing_rule_json,
  sleep_protocol_json, recovery_priority_json, sauna_ok, cryo_ok,
  reassessment_schedule_json, partner_hints_json, is_active
) VALUES (
  'BC-20', 'v1.0', 'ST-STOMACH형', '스트레스성 위장장애 체중 감소 방해형 — 위산 과다·소화력 저하',
  '복부 (위·소화기)',
  '스트레스받을 때 속이 쓰리고 밥맛이 없어지는 건 뇌와 장이 미주신경으로 직접 연결되어 있기 때문입니다. 스트레스가 위산을 교란합니다.',
  '만성 스트레스가 위산 분비를 불규칙하게 만들고 위 운동을 저하시킵니다. 소화 효율이 떨어지면 영양 흡수가 불완전해져 체중 관리가 어려워집니다.',
  '위가 아파도 먹어야 살이 빠진다', '소화력이 회복되면 영양 흡수가 살아납니다.',
  '["스트레스 받으면 속이 쓰림","식후 더부룩함·소화불량","공복에 위가 쓰림","역류성 식도염 증상","스트레스받으면 식욕 없어짐"]',
  '["위산억제제 장기복용","공복 커피","과도한 식사 제한"]',
  '["미주신경 활성화","규칙적 소량 식사","항스트레스 루틴"]',
  '[{"exercise":"복식 호흡","sets":3,"reps":"5분","note":"미주신경 활성화→위 운동 정상화"},{"exercise":"가벼운 걷기","sets":1,"reps":"20분","note":"위장 혈류 증가"},{"exercise":"요가 (복부 이완)","sets":1,"reps":"20분","note":"위장 긴장 완화"}]',
  '[{"exercise":"공복 고강도","reason":"위산 역류 악화"},{"exercise":"식후 즉시 운동","reason":"소화 혈류 방해"}]',
  120, 120, '10주 이후', '10주 이후',
  '["DGL 감초 추출물 380mg","소화 효소 복합체","프로바이오틱스","마그네슘 글리시네이트","L-글루타민 5g"]',
  '["커피 공복 (위산 자극)","맵고 자극적 음식","알코올","탄산음료","민트 (역류 악화)"]',
  '[{"name":"DGL 감초","dose":"380mg","timing":"식전 20분"},{"name":"소화효소","dose":"1캡슐","timing":"식사중"},{"name":"마그네슘 글리시네이트","dose":"400mg","timing":"취침전"}]',
  '["식사 전 3회 복식호흡","식사 시 스마트폰 금지","소량 자주 (5~6회)","식후 20분 휴식"]',
  '{"month1":"소화불량 빈도 50% 감소","month2":"공복 위 통증 완화","month3":"규칙적 소화 패턴 확립"}',
  '{"병원":[{"treatment":"위 내시경 (위염·역류 확인)","urgency":"medium","reason":"기질적 이상 확인"},{"treatment":"헬리코박터 검사+제균 치료","urgency":"medium","reason":"만성 위장 장애 원인 제거"}],"에스테틱":[{"treatment":"복부 경락 마사지","urgency":"medium","reason":"위장 혈류·연동 운동 개선"},{"treatment":"아로마 테라피 (라벤더·캐모마일)","urgency":"medium","reason":"스트레스성 위장 이완"}]}',
  '[{"test":"위 내시경","bc_indication":"BC-20","urgency":"medium"},{"test":"헬리코박터 호기 검사","bc_indication":"BC-20","urgency":"medium"}]',
  '[{"sport":"걷기 (식후 20분)","condition":"식후 안정 후","frequency":"매일","reason_bc":"위 혈류 개선"},{"sport":"요가 (이완)","condition":"식전","frequency":"주 3회","reason_bc":"미주신경 활성화"}]',
  '[{"sport":"공복 고강도","reason":"위산 역류 악화"},{"sport":"달리기 식후 즉시","reason":"소화 혈류 방해"}]',
  '{"protein_pct":25,"fat_pct":30,"carb_pct":45,"fiber_g":25,"water_L":2.0,"mineral_priority":["마그네슘","아연","B비타민"]}',
  '위는 스트레스에 가장 민감한 장기입니다. 편안한 마음으로 천천히 씹는 것이 최고의 소화제입니다.',
  '{"carb_last":false,"post_meal_walk_min":20,"fasting_allowed":false,"meal_interval_min":200}',
  '{"target_hours":7,"phone_ban_before_sleep_min":60,"bedroom_temp_celsius":20}',
  '[{"method":"복식호흡 (식전)","priority":1,"reason":"미주신경→위 운동 정상화"},{"method":"소화효소 복용","priority":2,"reason":"소화력 직접 보완"},{"method":"스트레스 관리","priority":3,"reason":"근본 원인 해소"}]',
  'true', 'false',
  '{"week4":"소화불량 빈도 변화","week8":"공복 위통 감소","week12":"소화 패턴 안정"}',
  '["위장 케어 프로그램","스트레스 관리 코칭","복부 마사지 패키지"]',
  1
);

-- BC-21: SK-SKIN형 (피부 노화·재생 저하형)
INSERT OR REPLACE INTO bc_prescriptions (
  bc_code, version, brand_name, tagline, fat_area,
  bc_primary_oneline_reason, bc_cause_story, bc_worsen_word, closing_copy,
  symptom_checklist_json, wrong_methods_json, correct_principles_json,
  recommended_exercises_json, forbidden_exercises_json,
  zone2_bpm, zone2_bpm_v2, hiit_available_week, hiit_available_week_v2,
  recommended_foods_json, forbidden_foods_json, supplement_list_json,
  lifestyle_rules_json, monthly_goals_json,
  b2b_treatments_json, hospital_tests_json,
  recommended_sports_json, forbidden_sports_json,
  macro_ratio_json, macro_story, meal_timing_rule_json,
  sleep_protocol_json, recovery_priority_json, sauna_ok, cryo_ok,
  reassessment_schedule_json, partner_hints_json, is_active
) VALUES (
  'BC-21', 'v1.0', 'SK-SKIN형', '피부 노화·재생 저하형 — 콜라겐 합성 감소·산화 스트레스 과잉',
  '피부 (탄력·수분·광채)',
  '피부가 처지고 주름이 늘어나는 건 시간이 지나서가 아닙니다. 콜라겐 합성 속도보다 분해 속도가 빨라진 것입니다.',
  '자외선·스트레스·당화 반응이 콜라겐을 분해하고 피부 재생을 방해합니다. 항산화 방어 시스템이 무너지면 피부 노화가 가속됩니다.',
  '나이 들면 원래 그래', '콜라겐을 지키고 항산화를 강화하면 피부는 회복됩니다.',
  '["피부 탄력 저하","잔주름 증가","피부 건조·푸석","칙칙한 피부 톤","상처 회복 느림"]',
  '["각질 제거 과잉","선크림 안 바르기","당분 과다 섭취 (당화 반응)"]',
  '["콜라겐 합성 영양소","항산화 강화","자외선 차단 철저"]',
  '[{"exercise":"존2 유산소","sets":1,"reps":"30분","note":"혈류 증가→피부 영양 공급"},{"exercise":"근력 운동","sets":3,"reps":"12회","note":"성장호르몬 분비→피부 재생"},{"exercise":"요가·명상","sets":1,"reps":"20분","note":"코르티솔 감소→콜라겐 보호"}]',
  '[{"exercise":"과도한 UV 노출 운동","reason":"광노화 가속"},{"exercise":"과도한 고강도 (산화 스트레스)","reason":"활성산소 증가→콜라겐 파괴"}]',
  125, 125, '4주 이후', '4주 이후',
  '["비타민C 1000mg (콜라겐 합성 보조)","콜라겐 펩타이드 10g","비타민E 400IU","아스타잔틴 12mg","CoQ10 200mg","아연 15mg"]',
  '["설탕·과당 (당화 반응 → 콜라겐 파괴)","트랜스지방","알코올 과다","흡연"]',
  '[{"name":"비타민C","dose":"1000mg","timing":"식후"},{"name":"콜라겐 펩타이드","dose":"10g","timing":"공복 또는 운동 후"},{"name":"아스타잔틴","dose":"12mg","timing":"식사중"},{"name":"비타민E","dose":"400IU","timing":"식사중"}]',
  '["SPF50+ 매일 사용","수분 2L 이상","설탕 급격히 감소","수면 8시간 확보"]',
  '{"month1":"피부 수분도 증가","month2":"탄력 개선 체감","month3":"주름 개선·광채 회복"}',
  '{"병원":[{"treatment":"피부 탄력·수분 측정 (코리오메터)","urgency":"low","reason":"피부 상태 정량화"},{"treatment":"콜라겐 부스팅 시술 (리프팅·스킨부스터)","urgency":"medium","reason":"콜라겐 직접 자극"}],"에스테틱":[{"treatment":"스킨부스터 (히알루론산 수분 주사)","urgency":"high","reason":"즉각 수분·탄력 공급"},{"treatment":"LED 광치료","urgency":"medium","reason":"콜라겐 합성 자극"},{"treatment":"고주파 리프팅","urgency":"medium","reason":"콜라겐 재생 가속"}]}',
  '[{"test":"피부 탄력 측정","bc_indication":"BC-21","urgency":"low"},{"test":"산화 스트레스 마커 (8-OHdG)","bc_indication":"BC-21","urgency":"low"}]',
  '[{"sport":"수영","condition":"자외선 차단 후 실내","frequency":"주 3회","reason_bc":"혈류 증가·피부 영양 공급"},{"sport":"요가","condition":"규칙적","frequency":"주 3회","reason_bc":"코르티솔 감소→콜라겐 보호"}]',
  '[{"sport":"오전 야외 운동 (자외선 강한 시간대)","reason":"광노화 가속"},{"sport":"과도한 HIIT","reason":"산화 스트레스 증가"}]',
  '{"protein_pct":30,"fat_pct":35,"carb_pct":35,"fiber_g":25,"water_L":2.5,"mineral_priority":["비타민C","아연","콜라겐"]}',
  '피부는 안에서 만들어집니다. 비타민C가 콜라겐을 꿰매고 아스타잔틴이 자외선을 막습니다.',
  '{"carb_last":false,"post_meal_walk_min":15,"fasting_allowed":false,"meal_interval_min":240}',
  '{"target_hours":8,"phone_ban_before_sleep_min":60,"bedroom_temp_celsius":19}',
  '[{"method":"수면 8시간 (성장호르몬)","priority":1,"reason":"콜라겐 합성 극대화"},{"method":"비타민C 매일 복용","priority":2,"reason":"콜라겐 합성 직접 보조"},{"method":"선크림 매일 SPF50+","priority":3,"reason":"광노화 차단"}]',
  'true', 'false',
  '{"week4":"피부 수분도 변화","week8":"탄력 개선","week12":"주름·광채 종합 평가"}',
  '["스킨부스터 패키지 추천","콜라겐 영양 프로그램","피부 재생 시술 연계"]',
  1
);

-- BC-22: AG-AGING형 (노화 가속 항산화 부족형)
INSERT OR REPLACE INTO bc_prescriptions (
  bc_code, version, brand_name, tagline, fat_area,
  bc_primary_oneline_reason, bc_cause_story, bc_worsen_word, closing_copy,
  symptom_checklist_json, wrong_methods_json, correct_principles_json,
  recommended_exercises_json, forbidden_exercises_json,
  zone2_bpm, zone2_bpm_v2, hiit_available_week, hiit_available_week_v2,
  recommended_foods_json, forbidden_foods_json, supplement_list_json,
  lifestyle_rules_json, monthly_goals_json,
  b2b_treatments_json, hospital_tests_json,
  recommended_sports_json, forbidden_sports_json,
  macro_ratio_json, macro_story, meal_timing_rule_json,
  sleep_protocol_json, recovery_priority_json, sauna_ok, cryo_ok,
  reassessment_schedule_json, partner_hints_json, is_active
) VALUES (
  'BC-22', 'v1.0', 'AG-AGING형', '노화 가속 항산화 부족형 — 텔로미어 단축·만성 산화 스트레스',
  '전신 (세포 노화)',
  '나이보다 더 빨리 늙는 것처럼 느껴지는 건 세포 시계가 빠르게 가고 있기 때문입니다. 활성산소가 텔로미어를 갉아먹고 있습니다.',
  '만성 스트레스·가공식품·환경 독소가 산화 스트레스를 폭증시킵니다. 항산화 방어 시스템이 이를 따라가지 못하면 세포 노화가 가속됩니다.',
  '나이 들면 어쩔 수 없어', '항노화는 특별한 사람만의 것이 아닙니다. 지금 시작하면 세포 시계를 늦출 수 있습니다.',
  '["나이보다 더 늙어 보인다","회복이 느리다","만성 질환 복수 보유","항산화 식품 거의 안 먹는다","스트레스·수면 부족 만성화"]',
  '["가공식품 지속","항산화 식품 무시","과도한 운동 산화"]',
  '["항산화 방어 극대화","텔로미어 보호","세포 재생 영양소 충분"]',
  '[{"exercise":"존2 유산소 (심장 강화)","sets":1,"reps":"45분","note":"텔로미어 연장에 가장 효과적인 운동"},{"exercise":"근력 운동","sets":3,"reps":"10회","note":"성장호르몬·IGF-1 분비→세포 재생"},{"exercise":"요가·명상","sets":1,"reps":"20분","note":"텔로머라제 활성화 (하버드 연구)"}]',
  '[{"exercise":"과도한 HIIT 매일","reason":"산화 스트레스 증가→텔로미어 단축"},{"exercise":"탈수 환경 운동","reason":"산화 스트레스 증폭"}]',
  130, 130, '8주 이후', '8주 이후',
  '["NMN 500mg (NAD+ 전구체)","레스베라트롤 500mg","아스타잔틴 12mg","CoQ10 300mg","알파리포산 600mg","비타민C 2000mg","비타민D3 5000IU"]',
  '["설탕·과당 (당화 노화)","트랜스지방","알코올 과다","흡연","초가공식품"]',
  '[{"name":"NMN","dose":"500mg","timing":"아침 공복"},{"name":"레스베라트롤","dose":"500mg","timing":"식사중"},{"name":"CoQ10","dose":"300mg","timing":"식사중"},{"name":"아스타잔틴","dose":"12mg","timing":"식사중"},{"name":"알파리포산","dose":"600mg","timing":"식전"}]',
  '["간헐적 단식 (16:8 가능)","햇빛 차단 (항노화 역설 - 저녁 산책 권장)","항산화 컬러 식품 매끼","스트레스 최소화"]',
  '{"month1":"산화 스트레스 마커 감소","month2":"에너지·회복력 향상","month3":"생물학적 나이 개선 체감"}',
  '{"병원":[{"treatment":"생물학적 나이 검사 (텔로미어 길이)","urgency":"low","reason":"노화 진행 속도 정량화"},{"treatment":"NAD+ 수액 (NMN 주사)","urgency":"medium","reason":"세포 에너지·재생 즉각 회복"},{"treatment":"고용량 비타민C 수액","urgency":"medium","reason":"항산화 즉각 강화"}],"에스테틱":[{"treatment":"항산화 수액 칵테일","urgency":"medium","reason":"전신 항산화 강화"},{"treatment":"크라이오테라피 (냉동 치료)","urgency":"medium","reason":"전신 항산화·회복 가속"}]}',
  '[{"test":"산화 스트레스 마커 (8-OHdG·MDA)","bc_indication":"BC-22","urgency":"low"},{"test":"텔로미어 길이 검사","bc_indication":"BC-22","urgency":"low"},{"test":"호모시스테인 (심혈관 노화 마커)","bc_indication":"BC-22","urgency":"medium"}]',
  '[{"sport":"존2 유산소 (자전거·수영)","condition":"규칙적","frequency":"주 4회 45분","reason_bc":"텔로미어 연장 입증된 운동"},{"sport":"요가·명상","condition":"규칙적","frequency":"주 4회","reason_bc":"텔로머라제 효소 활성화"}]',
  '[{"sport":"매일 과도한 HIIT","reason":"산화 스트레스 누적→텔로미어 단축"},{"sport":"탈수+자외선 동시 운동","reason":"산화 스트레스 극대화"}]',
  '{"protein_pct":30,"fat_pct":40,"carb_pct":30,"fiber_g":30,"water_L":2.5,"mineral_priority":["NMN","CoQ10","비타민C"]}',
  '세포 하나하나가 시계를 가지고 있습니다. NMN·레스베라트롤·아스타잔틴이 그 시계를 늦춥니다.',
  '{"carb_last":false,"post_meal_walk_min":15,"fasting_allowed":true,"meal_interval_min":480}',
  '{"target_hours":8,"phone_ban_before_sleep_min":90,"bedroom_temp_celsius":18}',
  '[{"method":"존2 유산소 주 4회","priority":1,"reason":"텔로미어 연장 최강 방법"},{"method":"NMN+레스베라트롤 복용","priority":2,"reason":"NAD+ 회복·시르투인 활성화"},{"method":"간헐적 단식 16:8","priority":3,"reason":"자가포식(오토파지) 활성화"}]',
  'true', 'true',
  '{"week4":"에너지·회복력 변화","week8":"산화 스트레스 재측정","week12":"생물학적 나이 재평가"}',
  '["항노화 프리미엄 패키지","NAD+ 수액 연계","항산화 토탈 프로그램"]',
  1
);
